### ISSUE TITLE
Matrix.to links violate RFC3986 (URI)

### ISSUE THREAD

**Issue by q9f** [matrix-org/matrix.to#251]
**Describe the bug**
A matrix.to invite link violates the rules for URIs defined in 3986 because of the `/#/#` part. An URI can only contain one `#` symbol.

**To Reproduce**
Steps to reproduce the behavior (Ruby 3.0 core rfc3986 URI parser):

```
❯ irb
irb(main):001:0> require 'uri'
=> true
irb(main):002:0> URI.parse 'https://matrix.to/'
=> #<URI::HTTPS https://matrix.to/>
irb(main):003:0> URI.parse 'https://matrix.to/#/'
=> #<URI::HTTPS https://matrix.to/#/>
irb(main):004:0> URI.parse 'https://matrix.to/#/#channel:example.com'
/home/user/.gem/ruby/3.0.0/gems/uri-0.11.0/lib/uri/rfc3986_parser.rb:67:in `split': bad URI(is not URI?): "https://matrix.to/#/#channel:example.com" (URI::InvalidURIError)
	from /home/user/.gem/ruby/3.0.0/gems/uri-0.11.0/lib/uri/rfc3986_parser.rb:72:in `parse'
	from /home/user/.gem/ruby/3.0.0/gems/uri-0.11.0/lib/uri/common.rb:188:in `parse'
	from (irb):4:in `<main>'
	from /usr/lib/ruby/gems/3.0.0/gems/irb-1.3.7/exe/irb:11:in `<top (required)>'
	from /usr/bin/irb:23:in `load'
	from /usr/bin/irb:23:in `<main>'
```

**Expected behavior**
Matrix links should be valid without two `#`. Possible alternatives:
* `https://matrix.to/#channel:example.com`
* `https://matrix.to/#/channel:example.com`
* `https://matrix.to/invite/#channel:example.com`

**Additional context**
* RFC 3986: https://datatracker.ietf.org/doc/html/rfc3986/#appendix-A
* Cannot add Matrix invites to Rails: https://github.com/forem/forem/issues/15719
* Ruby parser that fails the regex: https://github.com/ruby/ruby/blob/master/lib/uri/rfc3986_parser.rb#L67
* Related to #205 maybe?

**Comment by t3chguy** [comment]
This is mentioned in the README

> (Technically the # and @ in the URL fragment should probably be escaped, but in practice for legibility we bend the rules and include it verbatim)

**Comment by q9f** [comment]
Like this?

```ruby
irb(main):005:0> URI.parse 'https://matrix.to/#/%23channel:example.com'
=> #<URI::HTTPS https://matrix.to/#/%23channel:example.com>
```

**Comment by HarHarLinks** [comment]
> legibility

this commonly breaks matrix.to links copy-pasted to social media and other platforms using hashtags, as they auto-detect and -link URIs RFC-compliant and then auto-detect what appears to be hashtags after the first `#`
